# generated by datamodel-codegen:
#   filename:  protocol.schema.json

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Vec2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    x: float
    z: float


class Target(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    location: Annotated[
        str | None, Field(description='Named location from the room manifest')
    ] = None
    point: Vec2 | None = None
    user: bool | None = None


class Viseme(
    RootModel[
        Literal[
            'sil',
            'PP',
            'FF',
            'TH',
            'DD',
            'kk',
            'CH',
            'SS',
            'nn',
            'RR',
            'aa',
            'E',
            'I',
            'O',
            'U',
        ]
    ]
):
    root: Annotated[
        Literal[
            'sil',
            'PP',
            'FF',
            'TH',
            'DD',
            'kk',
            'CH',
            'SS',
            'nn',
            'RR',
            'aa',
            'E',
            'I',
            'O',
            'U',
        ],
        Field(description='Oculus 15-viseme set'),
    ]


class WordKey(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    t: Annotated[int, Field(ge=0)]
    w: str


class AvatarSnapshot(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    location: str | None
    position: Vec2
    heading_deg: float


class Audio(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tts_rate: int
    mic_rate: int


class SessionReadyData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    session_id: str
    resume_token: str
    manifest_version: str
    audio: Audio


class SessionReadyMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    type: Literal['session_ready']
    id: str
    ts: Annotated[int, Field(description='Unix ms')]
    data: SessionReadyData
    seq: Annotated[
        int, Field(description='Monotonic per session, used by resume', ge=0)
    ]


class WalkToData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cmd_id: str
    target: Target
    speed: Literal['walk', 'run'] | None = 'walk'
    face_on_arrival: str | None = 'default'
    interrupt: Literal['replace', 'queue'] | None = 'replace'


class WalkToMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    type: Literal['walk_to']
    id: str
    ts: Annotated[int, Field(description='Unix ms')]
    data: WalkToData
    seq: Annotated[
        int, Field(description='Monotonic per session, used by resume', ge=0)
    ]


class StopMovingData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cmd_id: str
    blend_ms: int | None = 300


class StopMovingMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    type: Literal['stop_moving']
    id: str
    ts: Annotated[int, Field(description='Unix ms')]
    data: StopMovingData
    seq: Annotated[
        int, Field(description='Monotonic per session, used by resume', ge=0)
    ]


class SpeechStartData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    utterance_id: str
    text: str
    voice: str | None = None


class SpeechStartMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    type: Literal['speech_start']
    id: str
    ts: Annotated[int, Field(description='Unix ms')]
    data: SpeechStartData
    seq: Annotated[
        int, Field(description='Monotonic per session, used by resume', ge=0)
    ]


class SpeechEndData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    utterance_id: str
    total_chunks: int


class SpeechEndMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    type: Literal['speech_end']
    id: str
    ts: Annotated[int, Field(description='Unix ms')]
    data: SpeechEndData
    seq: Annotated[
        int, Field(description='Monotonic per session, used by resume', ge=0)
    ]


class SpeechCancelData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    utterance_id: str
    reason: str


class SpeechCancelMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    type: Literal['speech_cancel']
    id: str
    ts: Annotated[int, Field(description='Unix ms')]
    data: SpeechCancelData
    seq: Annotated[
        int, Field(description='Monotonic per session, used by resume', ge=0)
    ]


class GestureData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cmd_id: str
    name: str
    layer: Literal['upper', 'full'] | None = 'upper'
    loop: bool | None = None
    blend_ms: int | None = 250


class GestureMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    type: Literal['gesture']
    id: str
    ts: Annotated[int, Field(description='Unix ms')]
    data: GestureData
    seq: Annotated[
        int, Field(description='Monotonic per session, used by resume', ge=0)
    ]


class LookAtData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cmd_id: str
    target: Target


class LookAtMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    type: Literal['look_at']
    id: str
    ts: Annotated[int, Field(description='Unix ms')]
    data: LookAtData
    seq: Annotated[
        int, Field(description='Monotonic per session, used by resume', ge=0)
    ]


class SetExpressionData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    weight: Annotated[float, Field(ge=0.0, le=1.0)]
    duration_ms: int | None = None


class SetExpressionMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    type: Literal['set_expression']
    id: str
    ts: Annotated[int, Field(description='Unix ms')]
    data: SetExpressionData
    seq: Annotated[
        int, Field(description='Monotonic per session, used by resume', ge=0)
    ]


class ListeningData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    mode: Literal['ptt', 'open_mic', 'off']


class ListeningMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    type: Literal['listening']
    id: str
    ts: Annotated[int, Field(description='Unix ms')]
    data: ListeningData
    seq: Annotated[
        int, Field(description='Monotonic per session, used by resume', ge=0)
    ]


class TranscriptData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: str
    final: bool


class TranscriptMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    type: Literal['transcript']
    id: str
    ts: Annotated[int, Field(description='Unix ms')]
    data: TranscriptData
    seq: Annotated[
        int, Field(description='Monotonic per session, used by resume', ge=0)
    ]


class ErrorData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: str
    ref: str | None = None
    message: str


class ErrorMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    type: Literal['error']
    id: str
    ts: Annotated[int, Field(description='Unix ms')]
    data: ErrorData
    seq: Annotated[
        int, Field(description='Monotonic per session, used by resume', ge=0)
    ]


class StateSyncData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    session_id: str
    last_seq: int
    avatar: AvatarSnapshot
    pending_cmds: list[str]
    speech: Literal['silent', 'talking', 'listening', 'thinking']


class StateSyncMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    type: Literal['state_sync']
    id: str
    ts: Annotated[int, Field(description='Unix ms')]
    data: StateSyncData
    seq: Annotated[
        int, Field(description='Monotonic per session, used by resume', ge=0)
    ]


class PongData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    t: int


class PongMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    type: Literal['pong']
    id: str
    ts: Annotated[int, Field(description='Unix ms')]
    data: PongData
    seq: Annotated[
        int, Field(description='Monotonic per session, used by resume', ge=0)
    ]


class Capabilities(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    visemes: str | None = None
    audio_driven_lipsync: bool | None = None
    mic_modes: list[Literal['ptt', 'open_mic']] | None = None


class HelloData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    client: str
    version: str
    room_id: str
    device: Literal['desktop', 'mobile'] | None = None
    capabilities: Capabilities | None = None
    output_latency_ms: int | None = None


class HelloMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    type: Literal['hello']
    id: str
    ts: Annotated[int, Field(description='Unix ms')]
    data: HelloData


class ResumeData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    session_id: str
    resume_token: str
    last_seq_received: int


class ResumeMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    type: Literal['resume']
    id: str
    ts: Annotated[int, Field(description='Unix ms')]
    data: ResumeData


class VisibilityData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    state: Literal['hidden', 'visible']


class VisibilityMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    type: Literal['visibility']
    id: str
    ts: Annotated[int, Field(description='Unix ms')]
    data: VisibilityData


class PingData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    t: int


class PingMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    type: Literal['ping']
    id: str
    ts: Annotated[int, Field(description='Unix ms')]
    data: PingData


class AckData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cmd_id: str


class AckMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    type: Literal['ack']
    id: str
    ts: Annotated[int, Field(description='Unix ms')]
    data: AckData


class WalkStartedData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cmd_id: str
    path_length_m: float
    eta_ms: int


class WalkStartedMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    type: Literal['walk_started']
    id: str
    ts: Annotated[int, Field(description='Unix ms')]
    data: WalkStartedData


class ArrivedData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cmd_id: str
    location: str | None = None
    position: Vec2


class ArrivedMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    type: Literal['arrived']
    id: str
    ts: Annotated[int, Field(description='Unix ms')]
    data: ArrivedData


class WalkFailedData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cmd_id: str
    reason: Literal['unreachable', 'unknown_location', 'blocked']
    nearest: Vec2 | None = None


class WalkFailedMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    type: Literal['walk_failed']
    id: str
    ts: Annotated[int, Field(description='Unix ms')]
    data: WalkFailedData


class CommandCancelledData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cmd_id: str
    reason: str


class CommandCancelledMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    type: Literal['command_cancelled']
    id: str
    ts: Annotated[int, Field(description='Unix ms')]
    data: CommandCancelledData


class SpeechStartedData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    utterance_id: str


class SpeechStartedMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    type: Literal['speech_started']
    id: str
    ts: Annotated[int, Field(description='Unix ms')]
    data: SpeechStartedData


class SpeechFinishedData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    utterance_id: str
    interrupted: bool
    played_ms: int
    last_word_index: int | None = None


class SpeechFinishedMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    type: Literal['speech_finished']
    id: str
    ts: Annotated[int, Field(description='Unix ms')]
    data: SpeechFinishedData


class GestureFinishedData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cmd_id: str
    name: str


class GestureFinishedMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    type: Literal['gesture_finished']
    id: str
    ts: Annotated[int, Field(description='Unix ms')]
    data: GestureFinishedData


class UserSpeechStartData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    segment_id: str
    while_: Annotated[
        Literal['idle', 'talking', 'walking'] | None, Field(alias='while')
    ] = None


class UserSpeechStartMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    type: Literal['user_speech_start']
    id: str
    ts: Annotated[int, Field(description='Unix ms')]
    data: UserSpeechStartData


class UserSpeechEndData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    segment_id: str
    duration_ms: int


class UserSpeechEndMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    type: Literal['user_speech_end']
    id: str
    ts: Annotated[int, Field(description='Unix ms')]
    data: UserSpeechEndData


class PttData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    state: Literal['down', 'up']


class PttMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    type: Literal['ptt']
    id: str
    ts: Annotated[int, Field(description='Unix ms')]
    data: PttData


class UserTextData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: str


class UserTextMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    type: Literal['user_text']
    id: str
    ts: Annotated[int, Field(description='Unix ms')]
    data: UserTextData


class StateData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    loco: Literal['idle', 'turning', 'walking', 'arriving']
    speech: Literal['silent', 'talking', 'listening', 'thinking']
    position: Vec2
    heading_deg: float


class StateMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    type: Literal['state']
    id: str
    ts: Annotated[int, Field(description='Unix ms')]
    data: StateData


class ClientMessage(
    RootModel[
        HelloMessage
        | ResumeMessage
        | VisibilityMessage
        | PingMessage
        | AckMessage
        | WalkStartedMessage
        | ArrivedMessage
        | WalkFailedMessage
        | CommandCancelledMessage
        | SpeechStartedMessage
        | SpeechFinishedMessage
        | GestureFinishedMessage
        | UserSpeechStartMessage
        | UserSpeechEndMessage
        | PttMessage
        | UserTextMessage
        | StateMessage
    ]
):
    root: Annotated[
        HelloMessage
        | ResumeMessage
        | VisibilityMessage
        | PingMessage
        | AckMessage
        | WalkStartedMessage
        | ArrivedMessage
        | WalkFailedMessage
        | CommandCancelledMessage
        | SpeechStartedMessage
        | SpeechFinishedMessage
        | GestureFinishedMessage
        | UserSpeechStartMessage
        | UserSpeechEndMessage
        | PttMessage
        | UserTextMessage
        | StateMessage,
        Field(title='ClientMessage'),
    ]


class VisemeKey(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    t: Annotated[int, Field(description='ms from chunk start', ge=0)]
    v: Viseme


class SpeechChunkData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    utterance_id: str
    stream_id: int
    seq: int
    sample_rate: int
    duration_ms: int
    visemes: list[VisemeKey] | None = None
    words: list[WordKey] | None = None
    last: bool


class SpeechChunkMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    type: Literal['speech_chunk']
    id: str
    ts: Annotated[int, Field(description='Unix ms')]
    data: SpeechChunkData
    seq: Annotated[
        int, Field(description='Monotonic per session, used by resume', ge=0)
    ]


class ServerMessage(
    RootModel[
        SessionReadyMessage
        | WalkToMessage
        | StopMovingMessage
        | SpeechStartMessage
        | SpeechChunkMessage
        | SpeechEndMessage
        | SpeechCancelMessage
        | GestureMessage
        | LookAtMessage
        | SetExpressionMessage
        | ListeningMessage
        | TranscriptMessage
        | ErrorMessage
        | StateSyncMessage
        | PongMessage
    ]
):
    root: Annotated[
        SessionReadyMessage
        | WalkToMessage
        | StopMovingMessage
        | SpeechStartMessage
        | SpeechChunkMessage
        | SpeechEndMessage
        | SpeechCancelMessage
        | GestureMessage
        | LookAtMessage
        | SetExpressionMessage
        | ListeningMessage
        | TranscriptMessage
        | ErrorMessage
        | StateSyncMessage
        | PongMessage,
        Field(title='ServerMessage'),
    ]


class Protocol(RootModel[ServerMessage | ClientMessage]):
    root: Annotated[
        ServerMessage | ClientMessage,
        Field(
            description='Kamari avatar WebSocket protocol v1. Source of truth for generated Python and TypeScript types. Binary audio frames: [u8 kind][u32 stream_id][u32 seq][payload], header big-endian, PCM16 payload little-endian; kind 0x01 = mic PCM16 16 kHz (client to server), 0x02 = TTS PCM16 (server to client).',
            title='Protocol',
        ),
    ]
